---
title: "Class Practice Penguin Data"
author: "Avetis Mishegyan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../output/")
```

# Introduction

Today we are going to work with the penguin data to learn *RMarkdown*.

## Load Libraries

```{r}
library(tidyverse)
library(here)
library(kableExtra)
library(memer)
library(palmerpenguins)
```

## Inspect the Data

```{r}
glimpse(penguins)
```

## Data Analysis

```{r penguin_percent_size, out.width="50%"}
penguins %>% # using the penguin dataset
  ggplot(aes(x = bill_length_mm,
             y = bill_depth_mm,
             color = species)) +
  geom_point() +
  geom_smooth(method = "lm") + # adds a linear regression
  labs(x = "Bill Length (mm)",
       y = "Bill Depth (mm)",
       color = "Species") +
  theme_bw()
```

```{r penguin_inch_size, fig.width=3, fig.height=4, fig.align='center'}
penguins %>% # using the penguin dataset
  ggplot(aes(x = bill_length_mm,
             y = bill_depth_mm,
             color = species)) +
  geom_point() +
  geom_smooth(method = "lm") + # adds a linear regression
  labs(x = "Bill Length (mm)",
       y = "Bill Depth (mm)",
       color = "Species") +
  theme_bw()
```

```{r penguin_aspect_size, fig.asp=1.2, fig.align='center', fig.cap="This is my penguin figure", echo=FALSE}
penguins %>% # using the penguin dataset
  ggplot(aes(x = bill_length_mm,
             y = bill_depth_mm,
             color = species)) +
  geom_point() +
  geom_smooth(method = "lm") + # adds a linear regression
  labs(x = "Bill Length (mm)",
       y = "Bill Depth (mm)",
       color = "Species") +
  theme_bw()
```

| Time | Session | Topic |
|:-----|:--------:|------:|
| _left_ | _center_ | _right_ |
| 1 | 2 | 3 |

```{r penguin_table}
penguins %>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>% # makes it a kable table
  kable_classic() %>%
  row_spec(2, bold = TRUE, color = "white", background = "red") %>%
  kable_styling(full_width = FALSE)
```

```{r meme}
meme_get("DistractedBf") %>% 
  meme_text_distbf("Silly R package", "BIOL 551 students", "actual coding")
```
